include classpath("application.conf")

whisk {
  couchdb {
    protocol = "http"
    host     = "163.239.199.209"
    port     = "5984"
    username = "admin"
    password = "dcclab"
    provider = "CouchDB"
    databases {
      WhiskAuth       = "whisk_local_subjects"
      WhiskEntity     = "whisk_local_whisks"
      WhiskActivation = "whisk_local_activations"
    }
  }
  }
